name: Ruby Minitest Dispatch

on:
  push:
    # branches:
    #   - main  # Change this to your default branch if needed
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Minitest
      run: rake -v -t test

  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Minitest
      run: |
        rake rubocop
